# thanks -> http://blogs.perl.org/users/alex_balhatchet/2013/04/travis-ci-perl.html
language: perl
perl:
#  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
  - "5.10"
before_install:
  # Prevent "Please tell me who you are" errors for certain DZIL configs
  - git config --global user.name "TravisCI"
install:
  # Deal with all of the DZIL dependancies, quickly and quietly
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - cpanm --quiet --notest --skip-satisfied Test::Perl::Critic
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - dzil listdeps | grep -vP '[^\w:]' |  xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest Dist::Zilla::App::Command::cover
  - wget https://raw.githubusercontent.com/KSP-CKAN/CKAN/master/bin/ckan-validate.py
  - wget https://raw.githubusercontent.com/KSP-CKAN/CKAN/master/CKAN.schema
  - chmod +x ckan-validate.py
  - python -V
  - ./test.py
  - pip install --user json-schema-validator
  - ls -lah ~/.local/lib/python2.7/site-packages/
script:
  - dzil test -v
  - ./ckan-validate.py t/data/CKAN-meta-validate/DogeCoinFlag/DogeCoinFlag-v1.02.ckan
  - python ckan-validate.py t/data/CKAN-meta-validate/DogeCoinFlag/DogeCoinFlag-v1.02.ckan
after_success:
  - dzil cover -outputdir cover_db -report coveralls
