# thanks -> http://blogs.perl.org/users/alex_balhatchet/2013/04/travis-ci-perl.html
language: perl
perl:
#  - "5.22"
  - "5.20"
  - "5.18"
addons:
  apt:
    sources:
    - git-core
    packages:
    - git
    - aspell
before_install:
  # Prevent "Please tell me who you are" errors for certain DZIL configs
  - git config --global user.name "TravisCI"
install:
  # Deal with all of the DZIL dependencies, quickly and quietly
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - cpanm --quiet --notest --skip-satisfied Test::Perl::Critic
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - dzil listdeps | grep -vP '[^\w:]' |  xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest Dist::Zilla::App::Command::cover
script:
  - git --version
  - dzil test
after_success:
  - dzil cover -outputdir cover_db -report coveralls
