package App::KSP_CKAN;

use v5.010;
use strict;
use warnings;
use autodie;
use Moo;
use Method::Signatures 20140224;
use Carp qw(croak);

# ABSTRACT: A collection of CKAN related tools

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

Don't have one yet!

=head1 DESCRIPTION

I don't even know yet :)

=cut

1;
