package App::KSP_CKAN::Roles::Validate;

use v5.010;
use strict;
use warnings;
use autodie;
use Method::Signatures 20140224;
use Capture::Tiny qw(capture);
use File::chdir;
use Moo::Role;

# ABSTRACT: Small validation role for consuming

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  with('App::KSP_CKAN::Roles::Validate');

=head1 DESCRIPTION

Currently lightly wraps ckan_validate.py. Requires ckan_validate.py
and CKAN.schema be in '$config->working'. Also requires consuming
class to have the Logger role.

=cut

requires 'config', 'warn';

=method validate

  $self->validate( file => "/path/to/file.pl" );

Validates the CKAN file at the path. Returns the exit
code captured (anything not '0' is considered a failure).

=cut

method validate($file) {
  my ($stderr, $stdout, $exit) = capture { 
    local $CWD = $self->config->working;
    system("python", "ckan-validate.py", $file);
  };

  $self->warn($stdout) if $stdout;
  return $exit;
}

1;
