package App::KSP_CKAN::Tools::Http;

use v5.010;
use strict;
use warnings;
use autodie;
use Method::Signatures 20140224;
use HTTP::Tiny;
use Moo;
use namespace::clean;

# ABSTRACT: A thin wrapper around Http::Tiny

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  use App::KSP_CKAN::Http;

  my $http = App::KSP_CKAN::Http->new();

=head1 DESCRIPTION

Provides thinly wrapped http functionality.

=cut

has '_http'   => ( is => 'ro', lazy => 1, builder => 1 );

method _build__http {
  return HTTP::Tiny->new( timeout => 15, verify_SSL => 1 );
}

=method mirror

  $http->mirror( url => $url, path => "/path/to/file.pl );

Has an optional argument 'exe' which will mark it
executable for the current user.

=cut

method mirror(:$url,:$path,:$exe = 0) {
  my $response = $self->_http->mirror($url,$path);

  if ($exe) {
    chmod(0755, $path);
  }
  
  return;
}

1;
